image:
  # -- repository with airsonic-advanced image
  repository: linuxserver/airsonic-advanced
  # -- current version of the image
  tag:
  # -- pull policy
  pullPolicy: IfNotPresent

# -- imagePullSecrets (not needed, if default image is used)
imagePullSecrets: []

# -- @ignore
nameOverride: ""
# -- @ignore
fullnameOverride: ""

persistence:
  # -- enable persistence when true
  enabled: false
  # -- actual storageClass
  storageClass: ""
  # -- default storage size
  size: 8Gi
  # -- accessMode
  accessMode: ReadWriteOnce

env:
  # -- URI path on tomcat
  contextPath: /
  # -- user id for container
  puid: 1000
  # -- group id for container user
  pgid: 1000
  # -- timezone, airsonic-advanced will use
  timezone: Etc/UTC

nfsMounts:
  # -- enable mounting of nfs exports
  enabled: false
  mounts:
    # -- name of mount
    - name: music
      # -- ip or dns of nfs server
      nfsServer: xxx.xxx.xxx.xxx
      # -- export path on nfs server
      exportPath: "/music"
      # -- mount path on container
      mountPath: "/music"
      # -- desired capacity (usually not needed for nfs)
      capacity: 20Gi
      # -- mark mount as readonly
      readOnly: false

serviceAccount:
  # -- enable serviceAccount
  create: true
  # -- add annotations to serviceAccount
  annotations: {}
  # -- name of the serviceAccount (will be generated if empty)
  name: ""

# -- @ignore
podAnnotations: {}

# -- @ignore
podSecurityContext: {}
  # fsGroup: 2000

# -- @ignore
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

# -- Configure ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- @ignore
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- @ignore
nodeSelector: {}

# -- @ignore
tolerations: []

# -- @ignore
affinity: {}
