{{- if .Values.nfsMounts.enabled -}}
{{- range .Values.nfsMounts.mounts }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "airsonic-advanced.fullname" $ }}-{{ .name }}-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .capacity }}
{{- end }}
{{- end }}
