{{- if .Values.nfsMounts.enabled -}}
{{- $relnamespace := .Release.Namespace -}}
{{- range .Values.nfsMounts.mounts }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ include "airsonic-advanced.fullname" $ }}-{{ .name }}-pv
spec:
    storageClassName: local-storage
    capacity:
        storage: {{ .capacity }}
    accessModes:
        - ReadWriteMany
    claimRef:
        namespace: {{ $relnamespace }}
        name: {{ .name }}-pvc
    nfs:
        server: {{ .nfsServer }}
        path: {{ .exportPath | quote }}
        readOnly: {{ .readOnly }}
{{- end }}
{{- end }}
